---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fastapi-backend
  name: fastapi-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-backend-app
  template:
    metadata:
      labels:
        app: fastapi-backend-app
    spec:
      containers:
      - name: app
        image: fastapi_backend:latest
        readinessProbe:
          httpGet:
            path: /api/health
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: FASTAPI_BACKEND_HOST
          value: "0.0.0.0"
        - name: FASTAPI_BACKEND_WORKERS_COUNT
          value: "10"
        - name: FASTAPI_BACKEND_DB_HOST
          value: "fastapi-backend-db-service"
        - name: FASTAPI_BACKEND_REDIS_HOST
          value: "fastapi-backend-redis-service"
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
          name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: fastapi-backend
  name: fastapi-backend-app-service
spec:
  selector:
    app: fastapi-backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: api-port
    name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-backend-app
  namespace: fastapi-backend
  labels:
    name: fastapi-backend-app
spec:
  rules:
  - host: fastapi-backend.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: fastapi-backend-app-service
            port:
              name: api-port

---
