version: '3.9'

services:
  db:
    image: postgres:alpine3.18
    hostname: fastapi_backend-db
    environment:
      POSTGRES_PASSWORD: "fastapi_backend"
      POSTGRES_USER: "fastapi_backend"
      POSTGRES_DB: "fastapi_backend"
    volumes:
    - fastapi_backend-db-data:/var/lib/postgresql/data
    restart: always
    ports:
    - 5432:5432
    healthcheck:
      test: pg_isready -U fastapi_backend
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2.13-alpine3.18
    hostname: "fastapi_backend-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5


  migrator:
    image: fastapi_backend:${FASTAPI_BACKEND_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      FASTAPI_BACKEND_DB_HOST: fastapi_backend-db
      FASTAPI_BACKEND_DB_PORT: 5432
      FASTAPI_BACKEND_DB_USER: fastapi_backend
      FASTAPI_BACKEND_DB_PASS: fastapi_backend
      FASTAPI_BACKEND_DB_BASE: fastapi_backend
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: fastapi_backend:${FASTAPI_BACKEND_VERSION:-latest}
    restart: always
    #command: bash -c 'ss=1; while ((ss)); do nc -vz fastapi_backend-kafka 9092; ss=$?; sleep 2; done;  echo kafka is up; /usr/local/bin/python -m fastapi_backend'
    command: /usr/local/bin/python -m fastapi_backend
    env_file:
    - .env
    ports:
    - ${FASTAPI_BACKEND_PORT:-8000}:8000
    labels:
      # Enables traefik for this container.
    - traefik.enable=true
    - traefik.http.routers.fastapi_backend.rule=Host(`${FASTAPI_BACKEND_TRAEFIK_HOST:-fastapi_backend.localhost}`)
    - traefik.http.routers.fastapi_backend.entrypoints=http
    - traefik.http.routers.fastapi_backend.service=fastapi_backend
    - traefik.http.services.fastapi_backend.loadbalancer.server.port=${FASTAPI_BACKEND_PORT:-8000}
    networks:
    - default
    - traefik-shared
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      FASTAPI_BACKEND_HOST: 0.0.0.0
      FASTAPI_BACKEND_DB_HOST: fastapi_backend-db
      FASTAPI_BACKEND_DB_PORT: 5432
      FASTAPI_BACKEND_DB_USER: fastapi_backend
      FASTAPI_BACKEND_DB_PASS: fastapi_backend
      FASTAPI_BACKEND_DB_BASE: fastapi_backend
      FASTAPI_BACKEND_REDIS_HOST: fastapi_backend-redis
      FASTAPI_BACKEND_CELERY_BROKER_URL: redis://fastapi_backend-redis:6379/0
      FASTAPI_BACKEND_CELERY_RESULT_BACKEND: redis://fastapi_backend-redis:6379/0

  worker:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: fastapi_backend:${FASTAPI_BACKEND_VERSION:-latest}
    command: celery -A fastapi_backend.celery worker --loglevel=info --concurrency=4
    volumes:
    - fastapi_backend-worker-data:/var/lib/worker/data
    environment:
      FASTAPI_BACKEND_CELERY_BROKER_URL: redis://fastapi_backend-redis:6379/0
      FASTAPI_BACKEND_CELERY_RESULT_BACKEND: redis://fastapi_backend-redis:6379/0
    depends_on:
    - redis

  beat:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: fastapi_backend:${FASTAPI_BACKEND_VERSION:-latest}
    command: celery -A fastapi_backend.celery beat --loglevel=info
    environment:
      FASTAPI_BACKEND_CELERY_BROKER_URL: redis://fastapi_backend-redis:6379/0
      FASTAPI_BACKEND_CELERY_RESULT_BACKEND: redis://fastapi_backend-redis:6379/0
    depends_on:
    - redis

  flower:
    image: mher/flower:2.0.1
    command: celery --broker=redis://fastapi_backend-redis:6379/0 flower --port=5555
    ports:
    - "5555:5555"
    depends_on:
    - worker
    - redis

volumes:
  fastapi_backend-db-data:
    name: fastapi_backend-db-data
  fastapi_backend-worker-data:
    name: fastapi_backend-worker-data

networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
